# Generated by Django 5.2.6 on 2025-09-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='skin_concern',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skin_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
